"""Stage 8 insight history: one row per hypothesis per evaluation day.

Stores only snapshot metadata (identity, evidence summary, wording and policy
versions), never a copy of the analytics dataset. The unique constraint on
(fingerprint, evaluated_on) is what makes the refresh operation idempotent:
the same hypothesis can be snapshotted at most once per calendar day, so a
repeated refresh or a page reload can never grow the history.

Revision ID: b2631e796164
Revises: d5a1c09e2401
Create Date: 2026-09-25 18:48:48.883661
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'b2631e796164'
down_revision: str | None = 'd5a1c09e2401'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insight_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('evaluated_on', sa.Date(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('x_key', sa.String(length=160), nullable=False),
    sa.Column('y_key', sa.String(length=160), nullable=False),
    sa.Column('x_label', sa.String(length=160), nullable=False),
    sa.Column('y_label', sa.String(length=160), nullable=False),
    sa.Column('grain', sa.String(length=16), nullable=False),
    sa.Column('lag', sa.Integer(), nullable=False),
    sa.Column('lag_unit', sa.String(length=8), nullable=True),
    sa.Column('orientation', sa.String(length=16), nullable=False),
    sa.Column('relationship_method', sa.String(length=24), nullable=True),
    sa.Column('coefficient', sa.Float(), nullable=True),
    sa.Column('n', sa.Integer(), nullable=False),
    sa.Column('pair_coverage', sa.Float(), nullable=True),
    sa.Column('confidence', sa.String(length=24), nullable=True),
    sa.Column('guardrail_verdict', sa.String(length=24), nullable=False),
    sa.Column('presentation_status', sa.String(length=24), nullable=False),
    sa.Column('blocking_reasons', sa.JSON(), nullable=False),
    sa.Column('warnings', sa.JSON(), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('insight_policy_version', sa.String(length=16), nullable=False),
    sa.Column('guardrail_policy_version', sa.String(length=16), nullable=False),
    sa.Column('confidence_policy_version', sa.String(length=16), nullable=False),
    sa.Column('template_version', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_insight_snapshots')),
    sa.UniqueConstraint('fingerprint', 'evaluated_on', name='fingerprint_evaluated_on')
    )
    with op.batch_alter_table('insight_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_insight_snapshots_evaluated_on'), ['evaluated_on'], unique=False)
        batch_op.create_index(batch_op.f('ix_insight_snapshots_fingerprint'), ['fingerprint'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('insight_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_insight_snapshots_fingerprint'))
        batch_op.drop_index(batch_op.f('ix_insight_snapshots_evaluated_on'))

    op.drop_table('insight_snapshots')
    # ### end Alembic commands ###
