"""daily states

Revision ID: d5a1c09e2401
Revises: fc1efb50fa8d
Create Date: 2026-09-24 22:08:32.901934
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'd5a1c09e2401'
down_revision: str | None = 'fc1efb50fa8d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state_date', sa.Date(), nullable=False),
    sa.Column('mood', sa.Integer(), nullable=True),
    sa.Column('energy', sa.Integer(), nullable=True),
    sa.Column('wellbeing', sa.Integer(), nullable=True),
    sa.Column('sleep_status', sa.String(length=16), nullable=True),
    sa.Column('sleep_minutes', sa.Integer(), nullable=True),
    sa.Column('alcohol', sa.Boolean(), nullable=True),
    sa.Column('alcohol_detail', sa.String(length=200), nullable=True),
    sa.Column('gaming', sa.Boolean(), nullable=True),
    sa.Column('gaming_minutes', sa.Integer(), nullable=True),
    sa.Column('computer_overuse', sa.Boolean(), nullable=True),
    sa.Column('computer_minutes', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("computer_minutes IS NULL OR (typeof(computer_minutes) = 'integer' AND computer_minutes BETWEEN 0 AND 1440)", name=op.f('ck_daily_states_computer_minutes_range')),
    sa.CheckConstraint("energy IS NULL OR (typeof(energy) = 'integer' AND energy BETWEEN 1 AND 5)", name=op.f('ck_daily_states_energy_range')),
    sa.CheckConstraint("gaming_minutes IS NULL OR (typeof(gaming_minutes) = 'integer' AND gaming_minutes BETWEEN 0 AND 1440)", name=op.f('ck_daily_states_gaming_minutes_range')),
    sa.CheckConstraint("mood IS NULL OR (typeof(mood) = 'integer' AND mood BETWEEN 1 AND 5)", name=op.f('ck_daily_states_mood_range')),
    sa.CheckConstraint("sleep_minutes IS NULL OR (typeof(sleep_minutes) = 'integer' AND sleep_minutes BETWEEN 0 AND 1440)", name=op.f('ck_daily_states_sleep_minutes_range')),
    sa.CheckConstraint("sleep_status IS NULL OR sleep_status IN ('underslept', 'normal', 'overslept')", name=op.f('ck_daily_states_sleep_status_values')),
    sa.CheckConstraint("wellbeing IS NULL OR (typeof(wellbeing) = 'integer' AND wellbeing BETWEEN 1 AND 5)", name=op.f('ck_daily_states_wellbeing_range')),
    sa.CheckConstraint('alcohol IS NULL OR alcohol IN (0, 1)', name=op.f('ck_daily_states_alcohol_values')),
    sa.CheckConstraint('alcohol_detail IS NULL OR (alcohol IS 1 AND length(trim(alcohol_detail)) BETWEEN 1 AND 200)', name=op.f('ck_daily_states_alcohol_detail_consistency')),
    sa.CheckConstraint('computer_overuse IS NULL OR computer_overuse IN (0, 1)', name=op.f('ck_daily_states_computer_overuse_values')),
    sa.CheckConstraint('gaming IS NULL OR gaming IN (0, 1)', name=op.f('ck_daily_states_gaming_values')),
    sa.CheckConstraint('gaming_minutes IS NULL OR gaming IS 1 OR (gaming IS 0 AND gaming_minutes = 0)', name=op.f('ck_daily_states_gaming_minutes_consistency')),
    sa.CheckConstraint('mood IS NOT NULL OR energy IS NOT NULL OR wellbeing IS NOT NULL OR sleep_status IS NOT NULL OR sleep_minutes IS NOT NULL OR alcohol IS NOT NULL OR gaming IS NOT NULL OR computer_overuse IS NOT NULL OR computer_minutes IS NOT NULL OR note IS NOT NULL', name=op.f('ck_daily_states_nonempty')),
    sa.CheckConstraint('note IS NULL OR length(trim(note)) BETWEEN 1 AND 500', name=op.f('ck_daily_states_note_length')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_states')),
    sa.UniqueConstraint('state_date', name=op.f('uq_daily_states_state_date'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily_states')
    # ### end Alembic commands ###
